import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Gauge, ShieldCheck, Target, Zap } from "lucide-react";
import { NewsFooter, NewsHeader } from "@/components/public-news/news-shell";
import { siteUrl } from "@/lib/news/public";

export const metadata: Metadata = { title: "About", description: "About Aura Digital Intelligence, a technology publication for Fiji and the Pacific.", alternates: { canonical: `${siteUrl()}/about` } };
const values=[{icon:Target,title:"Fiji relevance",text:"Global technology matters when it changes decisions for local businesses."},{icon:ShieldCheck,title:"Verification first",text:"Independent evidence gates publishable claims before they become articles."},{icon:Zap,title:"Fast, not careless",text:"We monitor a broad source network while keeping publication standards strict."},{icon:Gauge,title:"Commercial usefulness",text:"We explain practical consequences, not just repeat product announcements."}];

export default function AboutPage(){return <main className="min-h-screen bg-[#080a0d] text-white"><NewsHeader/>
<section className="border-b border-white/10"><div className="mx-auto max-w-[1320px] px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><p className="adi-kicker">About the publication</p><h1 className="adi-display mt-3 max-w-5xl">Technology intelligence built for Fiji.</h1><p className="mt-5 max-w-3xl text-base leading-8 text-white/52 sm:text-lg">Aura Digital Intelligence is the editorial and research publication of Aura Digital Fiji. We turn significant technology developments into verified, practical context for Fiji businesses.</p></div></section>
<section className="bg-[#f1eee6] text-black"><div className="mx-auto max-w-[1240px] px-4 py-9 sm:px-6 lg:px-8 lg:py-12"><div className="grid gap-8 lg:grid-cols-2"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-black/45">Our vision</p><h2 className="mt-2 text-4xl font-black leading-[.98] tracking-[-0.055em]">Make global technology useful locally.</h2><p className="mt-4 text-sm leading-7 text-black/58">Most global technology coverage is written for larger markets. We focus on what developments mean for businesses operating in Fiji and the Pacific.</p></div><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-black/45">Our mission</p><h2 className="mt-2 text-4xl font-black leading-[.98] tracking-[-0.055em]">Filter noise. Verify claims. Explain impact.</h2><p className="mt-4 text-sm leading-7 text-black/58">We filter developments through independent evidence, originality checks and practical usefulness before publication.</p></div></div><div className="mt-12 grid gap-6 sm:grid-cols-2">{values.map(({icon:Icon,title,text})=><article key={title} className="border-t-2 border-black pt-5"><Icon size={22}/><h3 className="mt-4 text-2xl font-black tracking-[-0.04em]">{title}</h3><p className="mt-3 text-sm leading-7 text-black/55">{text}</p></article>)}</div></div></section>
<section className="adi-aura-band"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 px-4 py-8 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-black/55">Publisher</p><h2 className="mt-2 text-3xl font-black tracking-[-0.05em]">Aura Digital Fiji</h2><p className="mt-3 max-w-2xl text-sm font-semibold leading-7 text-black/62">Websites, ecommerce, applications, business email, security and IT systems built for Fiji businesses.</p></div><a href="https://auradigitalfiji.com" className="inline-flex items-center gap-2 border-b-2 border-black pb-1 text-xs font-black uppercase tracking-[0.12em]">Visit Aura Digital Fiji <ArrowUpRight size={13}/></a></div></section>
<div className="mx-auto max-w-[1240px] px-4 py-8 sm:px-6 lg:px-8"><Link href="/editorial-standards" className="text-[10px] font-black uppercase tracking-[0.12em] text-white/55 hover:text-white">Read our editorial standards →</Link></div><NewsFooter/></main>}
